
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxmkwxulnbcoidpfmicw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bWt3eHVsbmJjb2lkcGZtaWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MzkxNDUsImV4cCI6MjA1ODAxNTE0NX0.VEZdzpFGuG185w-Klf4ZHYW1Af8RLdOk1U3pU-B9xa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
